### ISSUE TITLE
Merge the "emulators" and "open-source emulators" sections

### ISSUE THREAD

**Issue by NieDzejkob** [gbdev/awesome-gbdev#108]
The two sections are far apart from each other, which makes things confusing. Moreover, Gambatte should also be in the open-source section, and having a section for one item, IMO, isn't a good idea.
Alternatively, the more noteworthy emulators like SameBoy, mGBA and mooneye-gb should be moved to the main emulators section, and everything else should be moved to MORE.md.

**Comment by avivace** [comment]
The main emulator section, the one listed after Software development, mentions the "best" and most suited emulators for software development. They offer debug and other useful features when developing GB homebrews.

The second section, is instead targeted at listing every emulator at a decent state, or with a particular emulation.

I too think the current situation is not ideal and certainly not clear, so I'm open to suggestions, with the premises I described here (opensource/"reference"/ emulator vs emulators for developing homebrews)

**Comment by ISSOtm** [comment]
Well, imho, a section dedicated to "every" emulator should go to MORE.md.
As to which emulators to include, I'd have only one section with the "best" emus; I think mGBA and SameBoy are good reference implementations.
Here's the emus I'd put in the section, in order, with reasons:
- BGB: widely used, trustable/stable software, still active, great for debugging and dev (beware mentioned that his goal with BGB was to make homebrew be developed faster and with better quality)
- SameBoy: complete implementation (think higan), also has debugging capabilities, but lacking except on macOS (bgb on Wine appears to be less problematic)
- mGBA: works fairly good though it's less accurate than the previous two, readable source code for the most part, fairly easy to grasp, replacement to VBA in a bunch of regards
- mooneye-gb: DID SOMEBODY SAY TEST ROMS???
- Gambatte: for historical reasons, and to show a performance-oriented but accurate impl

**Comment by NieDzejkob** [comment]
IMHO, @ISSOtm's solution is perfect.

**Comment by avivace** [comment]
Removed in @cdaa63313200507375e8cb16e713d2f94032e03d

**Comment by avivace** [comment]
https://github.com/gbdev/awesome-gbdev/commit/4bcc97a0fb18a8d3f85e7e302ab30520fe17abe3 and following commits handle this:

- The main list has now only BGB, Mooney (research, test roms), Gambatte (Historical, implementation), SameBoy(open source, debugger). If you want an emulator on the main list, open an Issue/PR explaining why it should be on focus / how is different from the others in the secondary list.
- EMULATORS.md now contains the big list of open source emulators
