### ISSUE TITLE
Move the repo to a neutral namespace

### ISSUE THREAD

**Issue by avivace** [gbdev/awesome-gbdev#109]
I remember this already coming up and today someone pinged me about this.

Should we move this repository to a (more) neutral organization instead of being under the namespace of my personal GitHub account?

The obvious choice would be our [gbdev](https://github.com/gbdev) organization.

**Comment by raphaklaus** [comment]
Totally agree. The benefits are many, this organization could have other interesting repositories about the Game Boy ecosystem just to say one.

Count on me if you need any help.

**Comment by tobiasvl** [comment]
I think that sounds like a good idea.

**Comment by MineRobber9000** [comment]
I agree, this sounds like a good idea.

(also, since when was I invited to the gbdev org?)

**Comment by avivace** [comment]
The repository is now under the [`gbdev`](https://github.com/gbdev) organisation namespace.
