### ISSUE TITLE
Note the accuracy of documentation listed

### ISSUE THREAD

**Issue by deltabeard** [gbdev/awesome-gbdev#111]
Some of the resources listed in the Documentation section do not contain accurate information about the Game Boy (Color). It would be helpful to note how accurate each document is. Possibly having an errata section for each document that isn't open for editing.

For example, it was noted that the document at http://marc.rawer.de/Gameboy/Docs/GBCPUman.pdf had inaccuracies throughout. It may be helpful to note what the issues are, or remove a link to the file if it's not usable at all for GB development.

Thanks.

**Comment by avivace** [comment]
Removed in https://github.com/gbdev/awesome-gbdev/commit/cdaa63313200507375e8cb16e713d2f94032e03d

**Comment by avivace** [comment]
Correction policy is now mentioned in CONTRIBUTING.md
