### ISSUE TITLE
`CONTRIBUTING.md` mentions a `GAMES.md` and `EMULATORS.md`

### ISSUE THREAD

**Issue by torch2424** [gbdev/awesome-gbdev#113]
Hello!

See https://github.com/gbdev/awesome-gbdev/blame/master/CONTRIBUTING.md#L38

I don't see those files, though I know we are currently restructuring a lot of things. I don't mind making the change if this isn't by design.

Thanks!

**Comment by avivace** [comment]
See https://github.com/gbdev/awesome-gbdev/commit/4bcc97a0fb18a8d3f85e7e302ab30520fe17abe3 and following commits (WIP).
