### ISSUE TITLE
Add link to website in repo description

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/awesome-gbdev#126]
The list can also be viewed online (http://gbdev.github.io/awesome-gbdev/), and I think it's a more pleasant read; I think it'd be a good idea to add that link in the repo's description.

**Comment by avivace** [comment]
Yep! It's still not mentioned because I want to work on the web version a bit, improving the style a bit and  injecting the linked parts so everything is scrollable in a single page (e.g. the EMULATORS page should be printed instead of a link pointing to it).

**Comment by ISSOtm** [comment]
The link has been there for a while now, this should be closed. :P
