### ISSUE TITLE
Add DMG-01 and it's companion book

### ISSUE THREAD

**Issue by torch2424** [gbdev/awesome-gbdev#130]
Saw this on Twitter: https://github.com/rylev/DMG-01

Emulator built in rust, but it has a well written companion book / guide on writing an emulator, that goes really in depth with memory and CPU. Seems to be unfinished, but would be great to have. Especially for it's CPU section.

**Comment by aaaaaa123456789** [comment]
It doesn't seem finished yet, sadly. The idea of a companion book is great, though.

**Comment by tobiasvl** [comment]
No Game Boy development tutorials are finished, hehe.

**Comment by avivace** [comment]
Yep, most of the resources in the form of "tutorials" are 'unfinished' anyway.

This is definitely something we want in the list.
