### ISSUE TITLE
Work Master OS

### ISSUE THREAD

**Issue by Murplugg** [gbdev/awesome-gbdev#148]
Found this oddball from the mid 2000s:
Seems to have been a fairly active and documented project, albeit in Russian. It's still on Archive.org, a translated link is provided below.
Demo: https://www.youtube.com/watch?v=HYzcNVzZHz0
Project page with some working downloads:
https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fweb.archive.org%2Fweb%2F20081226144317%2Fhttp%3A%2F%2Fworkmaster.ru%2Findex.php%3Fp%3D43

Should this go in the MORE.md ?

**Comment by ISSOtm** [comment]
Maybe in the list itself under Homebrew > Demos? Seems pretty awesome to me.
(Unless there's source, I'm opposed to putting it in the other subcategories)

**Comment by Murplugg** [comment]
Good point. Thought the source was there when I posted, but it's not. Seems this was a commercial product at some point before v3.20 became freeware in 2005. The dev history seems quite extensive: https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fweb.archive.org%2Fweb%2F20081226145840%2Fhttp%3A%2F%2Fworkmaster.ru%2Findex.php%3Fp%3D8

Homebrew > Demo list fits better, I agree.

**Comment by Murplugg** [comment]
Btw, there are more of these micro OS-es that runs on GBC / GBA, specifically:
Nut/OS (GBA): www.ethernut.de/api/group__xg_nut_arch_arm_gba.html

gbaunix: http://www.kernelthread.com/publications/gbaunix/, https://github.com/JALsnipe/gbaunix-0.0

µCUnix (GBC): Not sure where to begin, there are several pages here: https://www.google.com/search?q=uclinux+gameboy

**Comment by ISSOtm** [comment]
Anything GBA is out of the scope of this list but could be proposed at [awesome-gbadev](https://github.com/gbdev/awesome-gbadev).

As for µCUnix, I haven't tested it (unlike Work Master), so I'm neutral.

**Comment by avivace** [comment]
I think this fits the main list, being an experimental still functional project.

1. We do already have a similar project already on the list, under "Related Projects". I still think they should go there and not on the Homebrews list since they are usually larger projects.

I've added Workmaster OS just below the existing entry. 

2. The website is completely gone now, so we should mirror everything we can savage from the archive.org copy on gb-archive and maybe expose in a more accessible way the documentation and the downloads.

3. I've checked µCUnix and it's not related at all to GB/GBC, [but to GBA](https://tech.slashdot.org/story/04/09/08/1225208/running-ancient-unix-on-nintendo-gameboy).

In [this](https://github.com/gbdev/awesome-gbadev/issues/1) Issue I've listed the other resources you mentioned.

**Comment by Murplugg** [comment]
Ah my bad. I'll go over there instead. Late edit on my previous post btw, just ignore it.

**Comment by avivace** [comment]
No worries, thanks for the contributions

**Comment by redthing1** [comment]
> Found this oddball from the mid 2000s: Seems to have been a fairly active and documented project, albeit in Russian. It's still on Archive.org, a translated link is provided below. Demo: https://www.youtube.com/watch?v=HYzcNVzZHz0 Project page with some working downloads: https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fweb.archive.org%2Fweb%2F20081226144317%2Fhttp%3A%2F%2Fworkmaster.ru%2Findex.php%3Fp%3D43
> 
> Should this go in the MORE.md ?

I really wanted to try this, but the download page for workmaster leads to an archived version of this URL: http://www.workmaster.ru/files/GBA.zip

However, there don't seem to be any working captures of it. Does anyone have a copy?

**Comment by 360fun** [comment]
> However, there don't seem to be any working captures of it. Does anyone have a copy?

**better late than never**...they say 😜
https://www.gamebrew.org/wiki/Work_Master_OS_GB

**Comment by redthing1** [comment]
Hell yeah! Thanks!!

**Comment by avivace** [comment]
Amazing, we have to add this to Homebrew hub

**Comment by dmitry-shechtman** [comment]
Indeed.

I'll be down to translating it to proper English, but I'm going need somebody's help disassembling it.

**Comment by 360fun** [comment]
Maybe you can try contacting the dev to see if he's willing to publish the source code! ;)
