### ISSUE TITLE
List Review: (1) Introduction

### ISSUE THREAD

**Issue by avivace** [gbdev/awesome-gbdev#159]
See #158 for context

> 1- [The Game Boy, a hardware autopsy](https://www.youtube.com/playlist?list=PLu3xpmdUP-GRDp8tknpXC_Y4RUQtMMqEu).
> 2- [The Ultimate Game Boy Talk](https://media.ccc.de/v/33c3-8029-the_ultimate_game_boy_talk).
> 3- [Emulation of Nintendo Game Boy](https://github.com/Baekalfen/PyBoy/blob/master/PyBoy.pdf) - Overview of the Game Boy hardware with the perspective of building an emulator.

**Comment by avivace** [comment]
1. okay
2. okay
3. I'm not sure it is really more relevant than other "books" in Documentation, maybe move it down?
4. Are there other resources we could move up here? Something giving a nice overview without being a burden?
5. If we remove 3, this becomes a "video only" section. Are we okay with it?

**Comment by aaaaaa123456789** [comment]
1, 2: no comments
3: there's no difference between this and any of the blog-like entries in the "Emulator Development" section, so there's no good reason to keep this one out of the corresponding section and in a privileged position
4: the only thing I'd move is the official Nintendo manual, but it might be OK where it is
5: fine by me, but we might want to change the title in that case

**Comment by pinobatch** [comment]
And for accessibility's sake, see if permission is available to transcribe one or more of those videos to text.

**Comment by avivace** [comment]
@pinobatch The Game Boy talk should have a permissive license (it's from CCC 2017). I don't know about the other video series and couldn't find any info (we have to contact the author).

@ISSOtm Any opinion on this? Any other resource/book that could make use of the visibility on this section?
