### ISSUE TITLE
List Review: (2) Community

### ISSUE THREAD

**Issue by avivace** [gbdev/awesome-gbdev#160]
See #158 for context

>1 - [gbdev Discord Server](https://discord.gg/gpBxq85)
>2 - [`#gbdev` on EFnet](http://chat.efnet.org/?channels=gbdev) - IRC channel.
> 3- [gbdev.gg8.se Wiki](http://gbdev.gg8.se/wiki/articles/Main_Page)
>4 - [devrs.com/gb](http://devrs.com/gb) - Old home of the scene: examples, sources, complete documentation, guides, tutorials and various tools.

**Comment by avivace** [comment]
1. okay
2. okay
3. this wiki is essentialy pandocs
4. is this still relevant?
5. Add our twitter account?
6. Replace the wiki with the updated pandocs link (https://gbdev.github.io/pandocs) once we  port the tutorials too, there
7. add the forum https://gbdev.gg8.se/forums/

**Comment by aaaaaa123456789** [comment]
1, 2: no comments
3: agreed, and perhaps just drop the link and leave it in the documentation section, since it's not much of a community (the fact that everyone can edit it doesn't make it a community)
4: if you want to keep it, move it below anything that is active
5: not sure, since much like 3, a broadcast point is not a community (even though many people can listen to it)
6: agreed

**Comment by ISSOtm** [comment]
1 and 2 are OK imo
3- Agreed, just drop the wiki link.
4- No. I gave it a look, and it's just outdated, by the awesome list if anything.
5- No, it's not relevant for development, only showcase.
6- Yep

**Comment by pinobatch** [comment]
3+6. I agree that the forums can replace the wiki link. (They share the same authentication, for one.)

**Comment by avivace** [comment]
About 6: The twitter account is "community" in the sense that:

- We usually retweet user content, anything related to gbdev
- Developers can see what other developers are doing from that feed and interact with each other

**Comment by avivace** [comment]
Closing this as we reached an agreement. The twitter account/feed has been dropped.
