### ISSUE TITLE
"High resolution schematics" under "Game boy color" is a dead link

### ISSUE THREAD

**Issue by malapropistic** [gbdev/awesome-gbdev#177]
Pictures for posterity.

Link clicked:
<img width="306" alt="Screen Shot 2020-05-20 at 7 50 37 PM" src="https://user-images.githubusercontent.com/21048235/82511600-57cc3880-9ad3-11ea-9ff2-f4a0ab1e1276.png">

Error:
<img width="655" alt="Screen Shot 2020-05-20 at 7 49 59 PM" src="https://user-images.githubusercontent.com/21048235/82511610-5dc21980-9ad3-11ea-9931-740a2e2afeab.png">

**Comment by HDR** [comment]
Here is a mirror, https://drive.google.com/file/d/12nqIeyFbU3KmAoRjJdU234Q0mNtuKB87/view?usp=sharing i suggest re-hosting it as the drive link will probably be gone if i clean out my google drive.

**Comment by avivace** [comment]
Thank you @malapropistic and @HDR !

Unfortunately, it seems that those files comes from private/internal document so I'd rather not have them here or hosted under our projects.

It should be feasible to produce the same kind of document following [clean room design](https://en.wikipedia.org/wiki/Clean_room_design) principles.
