### ISSUE TITLE
Add SoundSystem to the Tool section

### ISSUE THREAD

**Issue by BlitterObjectBob** [gbdev/awesome-gbdev#189]
I've released [SoundSystem](https://github.com/BlitterObjectBob/GBSoundSystem), which is a modernized audio driver for GameBoy Tracker (aka the Paragon 5 music player).

Can this be added to the Tools section?

Thanks!

**Comment by avivace** [comment]
LGTM. Any opinion on this, @gbdev/awesome-gb?

**Comment by DuoDreamer** [comment]
I think this is fantastic, plus it adds a great example of clean code and documentation.
