### ISSUE TITLE
Music trackers section

### ISSUE THREAD

**Issue by avivace** [gbdev/awesome-gbdev#190]
Should we move music trackers to a separate section from the "Tools" one?

**Comment by DuoDreamer** [comment]
I think "Tools" is broad and could be broken up and organized into things like "Tools - Graphics, Tools - Sound, Tools - Assemblers/Compilers, Tools - Libraries" etc. The link heirarchy needs a review.

**Comment by avivace** [comment]
@DuoDreamer do you have some suggestions on a possible new hierarchy?
