### ISSUE TITLE
Some ASM templates do not compile anymore

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/awesome-gbdev#208]
Recent RGBDS updates have made breaking changes to the language, leading to some libraries not working anymore.

For example, the first link in the ["Boilerplates and libraries" section](https://gbdev.io/list.html#boilerplates-and-libraries), which is the first one a new ASM programmer is going to try, fails to build.

What should we do?

- Poke upstream
- Move them down
- Note which RGBDS version (and other deps?) these entries require
- Remove those entries outright

**Comment by stuaxo** [comment]
It's always worth poking upstream, about 1/10 times you'll get someone who will fix something in a few days, saving you having to do something else later.

**Comment by avivace** [comment]
I suggest to:

- Remove them from the list (or move them to MORE.md)
- Open an Issue upstream

In any case, it's time for RGBDS to provide some of that stuff "officially" and from their docs

**Comment by ISSOtm** [comment]
What stuff? The changelogs are very clear about breaking changes, since we're plenty aware how much they break. (Besides, unless impossible, we deprecate behavior that will be changed, so that a smooth transition is possible.)

**Comment by ISSOtm** [comment]
ping @avivace

**Comment by avivace** [comment]
> What stuff? The changelogs are very clear about breaking changes, since we're plenty aware how much they break. (Besides, unless impossible, we deprecate behavior that will be changed, so that a smooth transition is possible.)

I meant "RGBDS should provide some officially maintained templates". Aside from this, my solution here is in the previous message

**Comment by ISSOtm** [comment]
This role is essentially fulfilled by gb-boilerplate and gb-starter-kit, which I keep up to date.

**Comment by ISSOtm** [comment]
@avivace Shouldn't this be re-opened until the templates have been triaged?

**Comment by avivace** [comment]
> @avivace Shouldn't this be re-opened until the templates have been triaged?

This issue concerns the actions to be taken to handle this kind of resources. An approach has been decided (see my comment), so now you are free to follow it for each of the interested entry.

**Comment by ISSOtm** [comment]
Right, I'll document that procedure in the wiki.
