### ISSUE TITLE
How to handle removed resources?

### ISSUE THREAD

**Issue by avivace** [gbdev/awesome-gbdev#212]
If a resource gets removed upstream, and supposed we have mirrors (which we [should](https://github.com/gb-archive) generally have) what should happen to our links? 

Should the links just point to a mirrored location or should we honor the removal upstream?

In particular:

1) If the resource had a proper OSS license
2) If the resource had not a proper OSS license

**Comment by ISSOtm** [comment]
Imo, if there is a proper OSS license, the mirror ought to replace the dead link, as it's definitely public. (Think *Infinity* or *LibreSprite*, for example.)

If there isn't, I think it should be handled on a case-by-case basis, depending on upstream's decision/wishes, and the usefulness of the resource.
