### ISSUE TITLE
brok: link gets (wrongly) flagged as invalid URL

### ISSUE THREAD

**Issue by avivace** [gbdev/awesome-gbdev#213]
brok, the tool we use to flag broken and invalid links in the github actions CI, reports `- Invalid URL: https://gb-archive.github.io/salvage/tutorial_de_ensamblador/tutorial_de_ensamblador%20[La%20decadence].html` but https://gb-archive.github.io/salvage/tutorial_de_ensamblador/tutorial_de_ensamblador%20[La%20decadence].html is a valid link

**Comment by brainard52** [comment]
I get a 404 when visiting https://gb-archive.github.io/salvage/tutorial_de_ensamblador/tutorial_de_ensamblador%20%5BLa%20decadence%5D.html

**Comment by GreenAndEievui** [comment]
This link does appear to be broken, it should instead be: 
https://gb-archive.github.io/salvage/tutorial_de_ensamblador/tutorial_de_ensamblador_la_decadence.html

**Comment by avivace** [comment]
`https://gb-archive.github.io/salvage/tutorial_de_ensamblador/tutorial_de_ensamblador%20%5BLa%20decadence%5D.html` was recently changed to remove the escapped entities so at the moment it returns a 404, but before, it got an "invalid link" by `brok`, even if it was definitely there.
