### ISSUE TITLE
Replacing tetris disassembly

### ISSUE THREAD

**Issue by vinheim3** [gbdev/awesome-gbdev#217]
Hello. Firstly, this is an issue rather than a PR first since it involves potentially removing an item from the list
I'm referring to the currently listed Tetris disassembly. I could be wrong, but it seems mostly like a generated disassembly using symbols, rather than something that looks like source code, which is fine, but maybe not what people would look for when looking for a disassembly (understanding how some things in a game works)
I have a new repo I'm hoping to replace it with: [https://github.com/vinheim3/tetris-gb-disasm](https://github.com/vinheim3/tetris-gb-disasm)

Every line of code and data byte is fully explained. It also has some visualisations in docs/ that shows all screens/sprites, and the game state flow. It could do with some work, eg not a crappy Makefile, and further explanations, or a larger doc, of an entire concept, eg multiplayer or the sound engine, but I think it provides a decent starting point

**Comment by AntonioND** [comment]
I guess you are talking about https://github.com/osnr/tetris?

A 4 year old project, with only one commit, that is the output of a tool, doesn't even build...  Yeah, I don't think it's worth keeping in the list. Yours is actually decent.

**Comment by avivace** [comment]
I do think you can go ahead and open a PR, the resource you are proposing is clearly superior and more useful than the one we have. @ISSOtm mentioned that there are other Tetris disassemblies around, maybe you want to chime in?

**Comment by avivace** [comment]
We'll leave this open as we still have to discuss about the other Tetris dissasemblies are around

**Comment by ISSOtm** [comment]
Honestly, this disassembly does the job well. I just find it a bit hard to read as a disasm due to the directory structure, but I opened an issue there about that; so, we can close this.
