### ISSUE TITLE
DeadCScroll and GBSoundSystem both dead

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/awesome-gbdev#222]
[DeadCScroll](https://github.com/BlitterObjectBob/DeadCScroll) and [GBSoundSystem](https://github.com/BlitterObjectBob/GBSoundSystem) are dead, and @BlitterObjectBob hasn't replied yet to my pings for a couple days.

Apparently, [the only surviving version of DeadCScroll](https://github.com/search?q=deadcscroll) is [a fork of mine from when I was making PRs](https://github.com/ISSOtm/DeadCScroll), [the same for GBSoundSystem](https://github.com/search?q=gbsoundsystem) is [gb-archive's](https://github.com/gb-archive/GBSoundSystem).

What should we do?

**Comment by avivace** [comment]
> [DeadCScroll](https://github.com/BlitterObjectBob/DeadCScroll) and [GBSoundSystem](https://github.com/BlitterObjectBob/GBSoundSystem) are dead, and @BlitterObjectBob hasn't replied yet to my pings for a couple days.
> 
> Apparently, [the only surviving version of DeadCScroll](https://github.com/search?q=deadcscroll) is [a fork of mine from when I was making PRs](https://github.com/ISSOtm/DeadCScroll), [the same for GBSoundSystem](https://github.com/search?q=gbsoundsystem) is [gb-archive's](https://github.com/gb-archive/GBSoundSystem).
> 
> What should we do?

gb-archive fork for GBSoundSystem is okay as mirror and if we don't find anything better your fork can be copied into gb-archive.

Let's wait a week for @BlitterObjectBob

**Comment by ISSOtm** [comment]
Fixed by ef7650fcc1837563e2352bd4247bd29fea7e28cc
