### ISSUE TITLE
DotMatrixGame is down

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/awesome-gbdev#229]
[The archive](https://web.archive.org/web/20200124004957/http://www.dotmatrixgame.com/) includes downloads but not tutorials anymore. Should it be kept, then?

**Comment by avivace** [comment]
> [The archive](https://web.archive.org/web/20200124004957/http://www.dotmatrixgame.com/) includes downloads but not tutorials anymore. Should it be kept, then?

Are you sure tutorials are not available there anymore? I seem to be able to open them (check also the other captures)

**Comment by avivace** [comment]
In any case, I believe the source should be removed / moved to MORE.md as the software is not maintained since 2017

**Comment by ISSOtm** [comment]
I only have the words "Pong Flappy Bird Mr Bean".

**Comment by nitro2k01** [comment]
The website seems to be up again at this time. WHOIS says the domain was updated on 2022-03-01, which correlates with the time it was down. (Perhaps a server move.)

**Comment by avivace** [comment]
> The website seems to be up again at this time. WHOIS says the domain was updated on 2022-03-01, which correlates with the time it was down. (Perhaps a server move.)

A part from the website being online/offline, I think it quite lost the relevancy to stay in the "main" list, as the tool was last updated 4 years ago and it seems like it's superseded by GBDK.
