### ISSUE TITLE
Redirect old URL for "Choosing tools"/"To C or not to C" to new URL

### ISSUE THREAD

**Issue by pinobatch** [gbdev/awesome-gbdev#236]
The previous URL of the article "Choosing tools for Game Boy development" <https://gbdev.io/to_c_or_not_to_c.html> is 404 Not Found instead of the expected 301 Moved Permanently to the current URL <https://gbdev.io/guides/tools.html>. This breaks inbound links.

(<https://www.coranac.com/2008/09/to-c-or-not-to-c/> is still present although unrelated.)

**Comment by pinobatch** [comment]
If a 301 is not possible on GitHub Pages, perhaps a `meta` refresh is. https://stackoverflow.com/a/32465659/2738262

**Comment by avivace** [comment]
301 is fine to me, @pinobatch , you want to send a PR?

**Comment by pinobatch** [comment]
I had filed this issue against the wrong repository. I will prepare a pull request for the correct repository.
