### ISSUE TITLE
HTML page outdated?

### ISSUE THREAD

**Issue by daid** [gbdev/awesome-gbdev#241]
I just noticed the page at https://gbdev.io/resources.html
Doesn't contain all stuff that this repo contains, is that intentional?

**Comment by avivace** [comment]
Just updated

**Comment by daid** [comment]
Clear.

One of the first lines of the readme:

> You can find a (way cooler) web version of this list [here](https://gbdev.github.io/resources).

Implies that the lists are synced :) but looking at the diff I see why manual syncing isn't a huge issue.
