### ISSUE TITLE
Remove DevSound

### ISSUE THREAD

**Issue by DevEd2** [gbdev/awesome-gbdev#242]
I am no longer maintaining the original version of DevSound or the Lite version, so I feel it should be removed from the list or replaced with DevSound X.

**Comment by avivace** [comment]
@DevEd2 I agree with replacing it with DevSoundX, but it seems like it's still lacking basic documentation..

**Comment by DevEd2** [comment]
@avivace DevSound X has complete documentation, see here: [https://github.com/DevEd2/DevSoundX/blob/main/Docs/Format.txt](https://github.com/DevEd2/DevSoundX/blob/main/Docs/Format.txt)

**Comment by avivace** [comment]
> @avivace DevSound X has complete documentation, see here: [DevEd2/DevSoundX@`main`/Docs/Format.txt](https://github.com/DevEd2/DevSoundX/blob/main/Docs/Format.txt?rgh-link-date=2023-04-11T17%3A16%3A54Z)

Considering the user will land on the root of the repository, where I can only see a "TODO" in the "Integrating" chapter, could this manual be linked in the README?

**Comment by DevEd2** [comment]
> > @avivace DevSound X has complete documentation, see here: [DevEd2/DevSoundX@`main`/Docs/Format.txt](https://github.com/DevEd2/DevSoundX/blob/main/Docs/Format.txt?rgh-link-date=2023-04-11T17%3A16%3A54Z)
> 
> Considering the user will land on the root of the repository, where I can only see a "TODO" in the "Integrating" chapter, could this manual be linked in the README?

**Very** late reply, but I've finally updated the readme to include actual integration instructions and to link the format documentation.
