### ISSUE TITLE
Should we honor misspelled website titles?

### ISSUE THREAD

**Issue by tobiasvl** [gbdev/awesome-gbdev#34]
I just opened #33 which changes "Gameboy" to the correct "Game Boy" throughout the list, as a continuation of 573b31c and #8.

However, it does not take misspelled website titles into consideration. If someone has called their website something with "Gameboy" in it, I have changed that to the correct spelling in my pull request.

Do we want to honor people's misspellings or have the correct spelling consistently throughout?

**Comment by tobiasvl** [comment]
I can split #33 in two PRs if necessary, one that should be uncontroversial and one that only changes the website titles that can be approved later on if the consensus is that it's OK.

**Comment by ISSOtm** [comment]
I would approve sticking to the title misspellings, since that's how the resource is labeled. I don't believe there's a need for any more than this ; for example, the misspelling could be part of a pun, which would probably be kept for humor, but keeping it would introduce an exception to the "correct syntax in names" rule, if it were to be accepted.

**Comment by tobiasvl** [comment]
This seems to have been codified by 0a29939. I'll go ahead and close this then!

**Comment by avivace** [comment]
I'm reopening this: I think the list could enjoy a better standardisation of spellings. I revised @ISSOtm points and I don't think we ever had a pun misspelling or any other case of relevancy of that particular spelling.

**Comment by ISSOtm** [comment]
My opinion still is that a resource's name should be honoured as-is, given that the purpose is to label that resource, not the Game Boy itself. Fixing the name should be their responsibility, not ours.

OTOH, the resource could be referring to itself inconsistently, so enforcing the spelling in that case would sidestep those issues.
