### ISSUE TITLE
Assembly course from Withicha State Universiy

### ISSUE THREAD

**Issue by avivace** [gbdev/awesome-gbdev#98]
Original link:

http://cratel.wichita.edu/cratel/ECE238Spr08 ⋅ Center for Research in Arts, Technology, Education, and Learning (CRATEL) at Withicha State Universiy ⋅ ECE 238 ⋅ Spring 2008 ⋅ Machine and assembly language programming concepts that illustrate basic principles and techniques. Application through study of the Z80 chip and Gameboy programming assignments. 

The entire site `cratel.wichita.edu` is down. I've tried to recover it from Archive.org ([here](https://github.com/gb-archive/ECE238Spr08)) but the navigation is broken.

**Comment by Smelly-Ghost** [comment]
I know this one has been sitting for a while, but back in April 2018 I had actually found the site dead and none of the web archive links working as well so I reached out to the professor of the course and he told me he didn't have anything archived from the site prior to the university taking it down.

![Capture](https://user-images.githubusercontent.com/60049391/72674603-75a66580-3a2d-11ea-99cb-2858d3e74ef2.PNG)

**Comment by avivace** [comment]
Meh :(
Thank you for the update! Anyway, I'm not giving up hope and keeping this open in case someone happens to have this mirrored or at least downloaded the assets.

**Comment by Smelly-Ghost** [comment]
No problem! I had mentioned it on the #archive channel of the Discord server back in August, but just saw that there was an open issue for it so I thought I would just add what I knew. Hopefully someone's got copies of things backed up though.

**Comment by avivace** [comment]
New location: https://gb-archive.github.io/salvage/cratel_wichita_edu_cratel_ECE238Spr08/index.html
Many thanks to h0tp3ngu1n!

**Comment by nitro2k01** [comment]
Is that mirror complete, or just what could be retrieved from the WayBack Machine?

**Comment by avivace** [comment]
It's complete with a lot stuff not on the WayBack machine. There's a "missing_files.txt" listing everything we still couldn't retrieve
